### ISSUE TITLE
Moving from lock version 13.4.0 of react-native-svg

### ISSUE THREAD

**Issue by Viraj-10** [gluestack/gluestack-ui#995] opened 2023-09-06 12:10 UTC
### Description

Currently gluestack-ui is locked into react-native-svg version 13.4.0 

### Steps to reproduce

Install gluestack-ui and upgrade the version.

### gluestack-ui Version

latest

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by njt1982** [comment] 2023-09-06 12:21
https://github.com/gluestack/gluestack-ui/blob/ee9d6a4c11c315d70818483ac60014b13c431f7d/packages/themed/package.json#L67
https://github.com/gluestack/gluestack-ui/blob/ee9d6a4c11c315d70818483ac60014b13c431f7d/packages/themed/src/components/Icons/config.json#L4

Also a bunch of example/storybook references too..

Why is it locked? Is there some compatibility issue with anything newer? Or is it nothing more than a typo?

**Comment by Viraj-10** [comment] 2023-09-06 12:23
There is compatibility issue with newer versions. Working on it.

**Comment by Viraj-10** [comment] 2023-09-06 13:07
Hey @njt1982, Update on this. So these problem is caused when there multiple versions of `react-native-svg`. 
fix for this is use resolution in your `package.json`. This keeps only one version of `react-native-svg` in your project.

```
"dependencies": {
    "@gluestack-style/react": "^0.2.27",
    "@gluestack-ui/icon": "^0.1.6",
    "expo": "~49.0.8",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-svg": "^13.13.0"
  },
  "resolutions": {
    "react-native-svg": "13.13.0"
  },
  ```

**Comment by Viraj-10** [comment] 2023-09-09 05:42
Hey @njt1982, This Issue is fixed in latest version of `@gluestack-ui/themed`.

**Comment by RobertSasak** [comment] 2023-09-09 07:05
I can confirm that the latest `@gluestack-ui/themed@0.1.33` works with `react-native-svg@13.13.0` but not with `react-native-svg@13.4.0` as it is expected by `npx expo-doctor`.

**Comment by Viraj-10** [comment] 2023-09-09 07:21
Hey @RobertSasak, It should work with 13.4.0 as well.
Issue was not with gluestack-ui/themed it was due presence of two versions of react-native-svg. We have now just removed locked version of react-native-svg.
If it is still not running please do yarn why react-native-svg or npm why react-native-svg. There should be only one version of react-native-svg present in project.
Let us know if you still facing issues.

**Comment by RobertSasak** [comment] 2023-09-09 07:38
Thank you for explaining and adressing this issue so fast. As you can see bellow _@gluestack-ui/icon_ still requires _react-native-svg@13.13.0_. That explain why setting _react-native-svg_ to _13.13.0_ helped. 

Perhaps icon library also need a release.

```shell
➜  yarn why react-native-svg  
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "react-native-svg"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-native-svg@13.4.0"
info Has been hoisted to "react-native-svg"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@gluestack-ui#utils#react-native-svg"
   - Hoisted from "@gluestack-ui#themed#@gluestack-ui#actionsheet#@gluestack-ui#hooks#react-native-svg"
   - Hoisted from "@gluestack-ui#themed#@gluestack-ui#actionsheet#@gluestack-ui#transitions#react-native-svg"
   - Hoisted from "@gluestack-ui#themed#@gluestack-ui#actionsheet#@gluestack-ui#transitions#@gluestack-ui#react-native-aria#react-native-svg"
info Disk size without dependencies: "6.54MB"
info Disk size with unique dependencies: "8.1MB"
info Disk size with transitive dependencies: "10.23MB"
info Number of shared dependencies: 11
=> Found "@gluestack-ui/icon#react-native-svg@13.13.0"
info This module exists because "@gluestack-ui#themed#@gluestack-ui#icon" depends on it.
info Disk size without dependencies: "5.36MB"
info Disk size with unique dependencies: "6.92MB"
info Disk size with transitive dependencies: "9.05MB"
info Number of shared dependencies: 11
```

**Comment by makkarMeenu** [comment] 2023-09-11 14:15
@RobertSasak We have removed the `react-native-svg` dependency from `@gleustack-ui/icon`.  Users will now manually have to add react-native-svg to their projects. Please update  `@gluestack-ui/themed` to latest `0.1.36`.

**Comment by njt1982** [comment] 2023-09-12 09:37
Hmm - just tried to upgrade..

```
Could not resolve dependency:
peer react-native-svg@"13.4.0" from @gluestack-ui/themed@0.1.37
node_modules/@gluestack-ui/themed
  @gluestack-ui/themed@"^0.1.33" from the root project
```

_does some digging_

**Comment by njt1982** [comment] 2023-09-12 09:39
![image](https://github.com/gluestack/gluestack-ui/assets/384976/07d81659-524e-4069-88de-0dab5895a094)

Still seems to be depending on 13.4.0 for me...

**Comment by njt1982** [comment] 2023-09-12 09:40
https://github.com/gluestack/gluestack-ui/blob/1565be5be56fc860a2466c5da533a9ed4cd4e797/packages/themed/package.json#L86

Is ^ still relevant?

**Comment by njt1982** [comment] 2023-09-12 09:48
So I've upgraded to 0.1.37, but still seem to have 13.4.0 for RN SVG enforced... I even tried an `npm update --force` wondering if it needed to actually run through a full update to recalculate peer dependencies or something odd... but no.

I also tried the `resolutions` suggestion you made previously, but that didn't seem to do anything, either.

For now, I'm sticking on 13.4.0 - but it would be nice to have this fixed in case RN SVG issue some kind of security update in a version subsequent to 13.13.0 which we won't be able to use.

```
$  npm why react-native-svg
react-native-svg@13.4.0
node_modules/react-native-svg
  react-native-svg@"^13.4.0" from the root project
  peer react-native-svg@"13.4.0" from @gluestack-ui/themed@0.1.37
  node_modules/@gluestack-ui/themed
    @gluestack-ui/themed@"^0.1.33" from the root project
```

^ in case its any help...

**Comment by makkarMeenu** [comment] 2023-09-21 07:08
Several versions of `react-native-svg` are not supported with some expo sdks versions.

While dealing with `react-native-svg` issues, we have come to the solution that we are keeping `"react-native-svg": ">=13.4.0"` in the peer dependencies of the themed library. Please update to the latest of `@gluestack-ui/themed` and add the issues if any in this thread to find better solutions.

**Closed** 2023-10-06 11:26 UTC
Labels: bug

**Comment by AkermanGreg** [comment] 2024-03-02 01:13
Hello,

I'm struggling with this issue as well, Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager

I'd appreciate any help


```
npm why react-native-svg
react-native-svg@13.14.0
node_modules/react-native-svg
  react-native-svg@"^13.4.0" from the root project
  peer react-native-svg@">=13.4.0" from @gluestack-ui/themed@1.1.9
  node_modules/@gluestack-ui/themed
    @gluestack-ui/themed@"^1.1.9" from the root project
    peer @gluestack-ui/themed@">=1.1" from @gluestack-ui/config@1.1.12
    node_modules/@gluestack-ui/config
      @gluestack-ui/config@"^1.1.2" from the root project
```
