### ISSUE TITLE
Toast component: Missing type definitions

### ISSUE THREAD

**Issue by schmitzc** [gluestack/gluestack-ui#883] opened 2023-08-22 21:57 UTC
### Description

Typescript errors when passing props to Toast component

### Steps to reproduce

Code:

```
toast.show({
      placement: 'top',
      render: () => {
        return (
          <Toast action="success">
            <ToastDescription>Your note was saved.</ToastDescription>
          </Toast>
        );
      },
    });
```

Typescript error:

```
error TS2322: Type '{ children: Element; action: string; }' is not assignable to type 'IntrinsicAttributes & Omit<ViewProps, "pointerEvents"> & Partial<ComponentProps<StyleProp<ViewStyle>, { pointerEvents: { auto: any; }; }, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'.
  Property 'action' does not exist on type 'IntrinsicAttributes & Omit<ViewProps, "pointerEvents"> & Partial<ComponentProps<StyleProp<ViewStyle>, { pointerEvents: { auto: any; }; }, ViewProps>> & Partial<...> & { ...; } & RefAttributes<...>'.

48           <Toast action="success">
                    ~~~~~~
```

### gluestack-ui Version

0.1.1 (@gluestack-ui/themed)

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by AshwiniKumar007** [comment] 2023-08-30 04:56
Hey @schmitzc,

We will check this. Thanks for reporting.

**Comment by ankit-tailor** [comment] 2023-08-31 14:10
Hey @schmitzc, The issue is fixed in the latest version. Let me know if it works for you.

**Closed by ankit-tailor** 2023-08-31 14:10 UTC
Labels: bug

**Comment by schmitzc** [comment] 2023-09-01 17:38
@ankit-tailor This is fixed for me. Thank you!
