### ISSUE TITLE
Metro is unable to resolve Unable to resolve @gluestack-ui/nativewind-utils

### ISSUE THREAD

**Issue by 1cedsoda** [gluestack/gluestack-ui#2410] opened 2024-08-25 12:08 UTC
### Description

Metro is unable to resolve Unable to resolve @gluestack-ui/nativewind-utils

### CodeSandbox/Snack link

https://codesandbox.io/p/devbox/gluestack-nativewind-utils-import-bug-shxl6r (works in this codesandbox but not locally)

### Steps to reproduce

1. Import `import { tva } from "@gluestack-ui/nativewind-utils";`
2. Use tva

Metro bundler error:

```
iOS Bundling failed 8571ms node_modules/expo-router/entry.js (3892 modules)
Unable to resolve "@gluestack-ui/nativewind-utils" from "components/custom/HrefButton.tsx"
```

Or

```
 ERROR  ReferenceError: Property 'tva' doesn't exist, js engine: hermes
Unable to resolve "@gluestack-ui/nativewind-utils" from "components/custom/HrefButton.tsx"
Error: While trying to resolve module `@gluestack-ui/nativewind-utils` from file `/Users/x/app/components/custom/HrefButton.tsx`, the package `/Users/x/app/node_modules/@gluestack-ui/nativewind-utils/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index`. Indeed, none of these files exist:

  * /Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css)
  * /Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css)
    at DependencyGraph.resolveDependency (/Users/x/app/node_modules/metro/src/node-haste/DependencyGraph.js:247:17)
    at /Users/x/app/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/x/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/x/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 0)
    at buildSubgraph (/Users/x/app/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
    at Graph._buildDelta (/Users/x/app/node_modules/metro/src/DeltaBundler/Graph.js:157:22)
    at Graph.traverseDependencies (/Users/x/app/node_modules/metro/src/DeltaBundler/Graph.js:49:19)
    at DeltaCalculator._getChangedDependencies (/Users/x/app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:187:42)
    at DeltaCalculator.getDelta (/Users/x/app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:68:16)
 ERROR  [Error: InternalError Metro has encountered an error: While trying to resolve module `@gluestack-ui/nativewind-utils` from file `/Users/x/app/components/custom/HrefButton.tsx`, the package `/Users/x/app/node_modules/@gluestack-ui/nativewind-utils/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index`. Indeed, none of these files exist:

  * /Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css)
  * /Users/x/app/node_modules/@gluestack-ui/nativewind-utils/src/index/index(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css): /Users/x/app/node_modules/metro/src/node-haste/DependencyGraph.js (247:17)

  245 |         }
  246 |         if (error instanceof InvalidPackageError) {
> 247 |           throw new PackageResolutionError({
      |                 ^
  248 |             packageError: error,
  249 |             originModulePath: from,
  250 |             targetModuleName: to,]
```

Fix:

Add tva path
`import { tva } from "@gluestack-ui/nativewind-utils/tva";`

### gluestack-ui Version

3.3.1

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Other Platform

supposedly all platforms

### Additional Information

`"@gluestack-ui/nativewind-utils": "^1.0.23",`

**Comment by shoma-mano** [comment] 2024-08-27 07:13
This issue arises because the package doesn't include the src directory when published, but the react-native field in the package.json points to src/index. Since Metro gives priority to the react-native field over other fields when resolving the package, this causes the problem.

**Comment by Viraj-10** [comment] 2024-09-23 10:31
Hey @shoma-mano, Could you please share a repository with a minimal reproduction of the issue?

**Comment by shoma-mano** [comment] 2024-09-23 14:12
@Viraj-10 
Hey! Thank for replying!
This is minimal reproduction.
1. `npx create-expo-app@latest`
2. `npx gluestack-ui init`  
3. `npm add @gluestack-ui/nativewind-utils`

https://github.com/shoma-mano/minimal-reproduction-2410

Error log says they referenced main filed to resolve the package, but  I think they referenced react-native filed actually.

**Comment by sra1kumar-NULL** [comment] 2024-09-25 07:27
hey @shoma-mano , This is not a bundle library you cannot import it from the index. You have to specify which package/file you have to import from . Ideally it should be imported something like this.
```import { tva } from "@gluestack-ui/nativewind-utils/tva";```

**Closed by sra1kumar-NULL** 2024-09-25 07:27 UTC
Labels: bug

**Comment by sirus-max** [comment] 2024-09-27 12:48
i am getting the following error:
Unable to resolve "@gluestack-ui/nativewind-utils/useBreakpointValue" while using grid component

When i opened the @gluestack-ui/nativewind-utils it does not even have the useBreakpointValue


@gluestack-ui/nativewind-utils/index.ts
```
export { tva } from './tva';
```

@gluestack-ui/nativewind-utils/index.d.ts
```
export { tva } from './tva';
export type { VariantProps } from './types';
```

**Comment by sirus-max** [comment] 2024-09-27 12:56
Issue: Missing useBreakpointValue in @gluestack-ui/nativewind-utils

I encountered an issue when trying to use the Grid component, which throws the following error:

```
Unable to resolve "@gluestack-ui/nativewind-utils/useBreakpointValue"
```

Upon inspecting the @gluestack-ui/nativewind-utils package, I noticed that the useBreakpointValue function is missing. 
There is no reference or implementation for useBreakpointValue within the package. Could you clarify if this function is missing or should be implemented elsewhere? Any guidance on resolving this issue would be appreciated.

**Comment by Viraj-10** [comment] 2024-09-27 12:59
Hey @sirus-max, I have recently removed `useBreakpointValue` from ` @gluestack-ui/nativewind-utils`. 
Please do the following. 
- run `npx gluestack-ui add useBreakpointValue`.
- replace import from `@gluestack-ui/nativewind-utils/useBreakpointValue`to `@/components/ui/utils/use-break-point-value`

**Comment by sirus-max** [comment] 2024-09-27 13:10
Thanks @Viraj-10 
The resolved the issue with useBreakpointValue and everything is working fine now.
Please update this in default installations of components as well.

Thanks for your help!

**Comment by sirus-max** [comment] 2024-09-30 12:43
Hi @Viraj-10,

I would like to confirm the current stability of Gluestack UI. I’ve been facing multiple issues with various components, particularly with the following:

	1.	Tabs Documentation: The documentation for the Tabs component is incomplete.
	2.	Installation Issues: I’m unable to install the Tabs component using the command:
	```
	npx gluestack-ui add tabs
	```
	3.	Grid Component Problems: The Grid component is also experiencing issues.

Could you please clarify if only the components listed on (https://gluestack.io/ui/docs/components/all-components) are considered stable?

**Comment by Viraj-10** [comment] 2024-09-30 12:48
Hey @sirus-max, Please use components which are available through sidebar. Some components are WIP and not yet exposed. 
Let me know what are the issues you are facing with `Grid`.

**Comment by JavanPoirier** [comment] 2024-12-20 22:58
Just ran into this myself, some further documentation may be useful.
