### ISSUE TITLE
Error reporting using input component

### ISSUE THREAD

**Issue by lilian132** [gluestack/gluestack-ui#869] opened 2023-08-18 05:14 UTC
### Description

Error reporting using InputInput

### Steps to reproduce

![image](https://github.com/gluestack/gluestack-ui/assets/4987042/092ee608-06ee-4ce9-9638-fbb5c7e8f170)

Very simple code, but there has always been this error
![image](https://github.com/gluestack/gluestack-ui/assets/4987042/74e6466c-31e3-44c5-aec7-93ee9c8dd77c)

### gluestack-ui Version

0.1.2

### Platform

- [X] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by makkarMeenu** [comment] 2023-08-18 06:59
This is breaking because tokens are not working in placeholderTextColor. We are working on these fixes.

**Comment by makkarMeenu** [comment] 2023-09-12 10:04
This is duplicate of https://github.com/gluestack/gluestack-ui/issues/829. Updates will be delivered on that issue.

**Closed by makkarMeenu** 2023-09-12 10:04 UTC
Labels: bug, good first issue
