### ISSUE TITLE
Android Only, Custom font Quicksand google not apply to Heading but apply well on Text.

### ISSUE THREAD

**Issue by ducpt-bili** [gluestack/gluestack-ui#1558] opened 2023-12-24 01:57 UTC
### Description

On Android (NOT ios), I am trying to custom font family on my react native project (with cli, not expo). Everything seem to work so far, but Heading is not apply font family at all, rare RN Text and gluestack Text seem fine. It's weird.

### Steps to reproduce

1. Copy quick sand font to fonts folder
2. Run npx react-native-asset to link assets, check android folder and it copy to it.
3. Apply font on my custom theme heading, body, mono.
4. I even try to change fontfamily on props of Heading or custom in Heading component in theme config but it not work.
5. Update lib to newest, try follow issue on github issue => Not work
"@gluestack-style/react": "^1.0.30",
"@gluestack-ui/config": "^1.0.10",
"@gluestack-ui/themed": "^1.0.31",

### gluestack-ui Version

1.0.10

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

[
<img width="590" alt="Screenshot 2023-12-24 at 08 54 44" src="https://github.com/gluestack/gluestack-ui/assets/101504153/a1a5b36e-d74b-424a-873d-5d9fce07b58a">
<img width="650" alt="Screenshot 2023-12-24 at 08 55 01" src="https://github.com/gluestack/gluestack-ui/assets/101504153/2c1fb48a-4d2b-4888-a626-7819812ab295">
](url)

**Comment by ducpt-bili** [comment] 2023-12-24 03:27
Just update:
- I trying using FontResolver but it not work. Please check below my image.
<img width="657" alt="Screenshot 2023-12-24 at 10 26 21" src="https://github.com/gluestack/gluestack-ui/assets/101504153/71a4c70e-fac8-4fce-ac1f-2692b51c32bd">
<img width="763" alt="Screenshot 2023-12-24 at 10 26 40" src="https://github.com/gluestack/gluestack-ui/assets/101504153/9d98dd0b-2ceb-4326-aa92-e803ebddf4b9">
<img width="306" alt="Screenshot 2023-12-24 at 10 27 13" src="https://github.com/gluestack/gluestack-ui/assets/101504153/9e7aebc1-39a7-4962-bcc6-73be06cba1b3">

**Comment by ducpt-bili** [comment] 2023-12-25 14:32
hi @Viraj-10 , maybe you can help me with this issue too. 
Thank a lot. I am trying my best to understand and using this lib like Native Base before.

**Comment by SandeepSagarPanjala** [comment] 2023-12-27 07:50
I'm facing the same issue
`Warning: Failed prop type: Invalid props.style key `variants` supplied to `Text`.`

**Comment by Jzuni97** [comment] 2023-12-30 00:10
Having a similar issue but instead the app just crashes with the following error:
`Error: You attempted to set the key `fontWeight` with the value `"$semibold"` on an object that is meant to be immutable and has been frozen.`

I am using expo google fonts and load correctly when using react-native Text component, i.e.
`<Text style={{ fontFamily: 'NunitoSans_400Regular' }}>Hello</Text>`.
But when using glustack's it throws the error.
I am also using the **FontResolver** with the following mapper:
```
const fontMapper = (style: any) => {
  let weight = "Regular";
  switch (style.fontWeight) {
    case "100":
      weight = style.fontFamily == "Nunito Sans" ? "ExtraLight" : "Thin";
      break;

    // All other font weight cases...
  }

  const fontFamily = `${style.fontFamily.replace(" ", "")}_${
    style.fontWeight
  }${weight}${style.fontStyle == "italic" ? "_Italic" : ""}`; // End result --> 'NunitoSans_100ExtraLight'

  style = { fontFamily };
  // Not sure if i'm supposed to return the style either..
};
```

**Comment by ducpt-bili** [comment] 2024-01-03 03:26
bump! Need support. :(

**Comment by Digital-Human-BK** [comment] 2024-01-05 19:39
Can someone from the GluestackUI team, tell us how to import fonts the proper way? I have this font installed in my React Native CLI project
![image](https://github.com/gluestack/gluestack-ui/assets/85568905/1d35fd50-d315-498f-be28-81cf73392565)
and I'm integrating it into the theme only by doing 
![image](https://github.com/gluestack/gluestack-ui/assets/85568905/7f630a43-07e6-46c1-8901-99fa3ac70bab)
Atm the font is applied for my Text components but works only on Regular and Bold. I can't make the other variants work too. Any suggestions or help will be greatly appreciated.

**Comment by Kasendwa** [comment] 2024-01-05 19:53
I have the same problem. For now I chose to leave avoid the Heading component and just use the Text component

Then pass a fontFamily prop to the Text component that will make pick up your custom font.

**Comment by Digital-Human-BK** [comment] 2024-01-05 22:48
> I have the same problem. For now I chose to leave avoid the Heading component and just use the Text component
> 
> Then pass a fontFamily prop to the Text component that will make pick up your custom font.

Yep, I found that solution as well. I don't like it, but it is what it is.

**Comment by Kasendwa** [comment] 2024-01-05 23:07
> > I have the same problem. For now I chose to leave avoid the Heading component and just use the Text component
> > Then pass a fontFamily prop to the Text component that will make pick up your custom font.
> 
> Yep, I found that solution as well. I don't like it, but it is what it is.

When I drilled down, I realised this issue seems to be caused from `@expo/html-elements` instead. The `Heading` component just cascades all resolved styles to the `H4` component of `@expo/html-elements`. Any way, not 100% certain but will dig deeper and see if I can raise a PR for it. 

Best half measure is to abstract the `Heading` component in a custom shared wrapper so that whenever the issue gets resolved, you don't need to do a lot of refactoring to go the right path.

**Comment by saoudnazir** [comment] 2024-01-24 05:09
Facing same issue.

**Comment by ankit-tailor** [comment] 2024-01-24 07:20
Hey @Digital-Human-BK, The fix will work for RN cli as well.  Can you share the github repo if it is possible? It will help me to debug the issue.

**Comment by saoudnazir** [comment] 2024-01-24 07:49
Hi @ankit-tailor, I have looked into you repo and used FontResolver in plugins but it seems not working.
Here is my config code:
![image](https://github.com/gluestack/gluestack-ui/assets/31433177/e3077789-2ecd-42d0-a503-69953cfa98c7)

Also, I have linked the Fonts in native projects.

**Comment by tedcu** [comment] 2024-01-26 11:06
Same issue. 
- Unable to change `fontFamily` for `Heading` on Android. Can't even change it to `Arial`.
- Initial font is always `Roboto`.
- No issues on iOS.

Versions:
```
"@gluestack-style/animation-resolver": "^1.0.3",
"@gluestack-style/react": "^1.0.43",
"@gluestack-ui/config": "^1.1.1",
"@gluestack-ui/themed": "^1.1.0",
```

Anyone able to use `Heading` as expected?

**Comment by rcasari1987** [comment] 2024-01-26 19:05
Title: Issue with Custom Fonts in React Native Project

Description:
I am facing the same issue - I can't get the font to work correctly in my React Native CLI project. I have local fonts installed using the method outlined in this guide: [link to the guide](https://aravindmnair.medium.com/add-custom-fonts-to-react-native-0-60-easily-in-3-steps-fcd71459f4c9). However, the fontResolver doesn't work for me on either Android or iOS. Without the fontResolver, it works on iOS, but only for the regular and bold fonts; the others are not functional.

**Dependencies versions:**

- **@gluestack-style/react:** ^1.0.43
- **@gluestack-ui/config:** ^1.1.1
- **@gluestack-ui/themed:** ^1.1.0



Any help or guidance on resolving this font issue would be greatly appreciated!

**Comment by Digital-Human-BK** [comment] 2024-01-26 21:28
Still doesn't work for me either. Can we have a reference for a working example? Also, can you add instructions in the [docs](https://gluestack.io/ui/docs/advanced/fonts) on using fonts in React Native CLI projects?

**Comment by zouchatj** [comment] 2024-01-28 05:22
Bumping for monitoring as I can am having the same problem where the Text component works correctly but other components aren't pulling it in (header, input placeholder)

**Comment by moeBabazadeh** [comment] 2024-01-28 16:26
For anyone interested in a solution, I've addressed this font issue. Check out the solution in my previous comment [here](https://github.com/gluestack/gluestack-ui/issues/788#issuecomment-1913649058). Feel free to test it, and if it works for you, I'm ready to create a pull request.

Thanks,
Moe

**Comment by ankit-tailor** [comment] 2024-01-29 11:29
Duplicate of #788.

**Closed by ankit-tailor** 2024-01-29 11:29 UTC
Labels: bug
