### ISSUE TITLE
Typescript missing component prop type definitions 

### ISSUE THREAD

**Issue by sarpere** [gluestack/gluestack-ui#1392] opened 2023-11-18 11:02 UTC
### Description

Component prop type definitions are missing for several component such as `FormControl`, `Checkbox`, `Select`.  This list may be extended after investigate how many missing type definitions exist. 

### Problem Statement

Types should have exported to extend custom component based in Gluestack lib.

### Proposed Solution or API

Expected export behavior 
import {
  FormControl,
  IFormControlProps,
} from '@gluestack-ui/themed';

### Additional Information

Environment versions 
@gluestack-ui/themed = 1.0.16

**Comment by ankit-tailor** [comment] 2023-11-22 11:02
Hey @sarpere, Thanks for reporting it. We will look into it.

**Comment by Viraj-10** [comment] 2023-11-28 12:03
closing this issue it is duplicate of #848. 
for now you can extract type using 

```
import { Button } from "@gluestack-ui/themed"

const IButtonProps = React.ComponentProps<typeof Button>
```
refer this [blog](https://www.totaltypescript.com/react-component-props-type-helper) for more info.

**Closed by Viraj-10** 2023-11-28 12:03 UTC
Labels: TypeScript
