### ISSUE TITLE
Modal components making typescript intellisense slower in VSCode

### ISSUE THREAD

**Issue by CarlosSLoureiro** [gluestack/gluestack-ui#927] opened 2023-08-31 16:36 UTC
### Description

When I try to use the example of modal component my VSCode intellisense for typescript makes VERY slow to load tips

### Steps to reproduce

Just try to apply the example of modal component:

https://ui.gluestack.io/docs/components/overlay/modal

### gluestack-ui Version

0.1.10

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment] 2023-09-01 04:29
Hey @CarlosSLoureiro, Can you try latest version?

**Comment by jack-pearson** [comment] 2023-10-27 06:06
I was really, really slow in version 1.0. Force me to use this awesome ui library in a way

**Comment by surajahmed** [comment] 2023-11-17 06:43
I understand this can be frustrating. We are actively addressing the issue, and we would appreciate it if you could update your typescript version to the latest in your project.

**Comment by ankit-tailor** [comment] 2023-12-08 12:58
Duplicate of #903.

**Closed by ankit-tailor** 2023-12-08 12:58 UTC
Labels: bug, TypeScript
