### ISSUE TITLE
Property 'ref' does not exist on type 'StyledComponentProps<StyleProp<ViewStyle>, unknown, ViewProps, "View">'

### ISSUE THREAD

**Issue by jayala** [gluestack/gluestack-ui#1668] opened 2024-01-18 12:28 UTC
### Description

Typescript shows an error when trying to use ref with styled components

### Steps to reproduce

1. Start a new project `npx create-expo-app@latest --template tabs@49`
2. Install gluestack-ui/themed (tested with 1.0.37)
3. Import View and try to pass a ref to it

![image](https://github.com/gluestack/gluestack-ui/assets/1461486/b133756c-47bf-407c-aeca-d8354a3a4e41)

### gluestack-ui Version

1.0.37

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by artfb** [comment] 2024-01-22 15:50
Bump, 
I'd like to request forwardingRef in `Input`

**Comment by educ-ai** [comment] 2024-02-14 20:13
`ref` isn't working on many elements, only `Button` seems to be working.

**Comment by educ-ai** [comment] 2024-02-14 21:20
`ref` isn't working on many elements, only some random components, like `Button` or `InputSlot` seem to be working.

For those who want to use a workaround:
```ts
type InputFieldProps = React.ComponentProps<typeof InputField>;
type HackedInputFieldProps = InputFieldProps & { ref?: any };
const HackedInputField = InputField as React.ComponentType<HackedInputFieldProps>;
```

Why this works: the prop is actually somewhere there, it's just not declared in the type.

**Comment by ankit-tailor** [comment] 2024-03-12 07:13
Hi Everyone, The issue is fixed in latest version of `@gluestack-style/react` and `@gluestack-ui/themed`. Let me know if that works for you.

**Closed by ankit-tailor** 2024-03-12 07:13 UTC
Labels: bug

**Comment by aahahocevar** [comment] 2024-03-12 07:58
Hello everyone,

I just tried in an InputField component, no more problem here:
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/20a2feb9-6ed4-4ade-8a36-f0e89f6097d1)

But the functions **isFocused()**, **blur()**, **focus()** and others are beeping :)
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/86900f58-9e40-471f-af6c-3786c66bec3d)

I'm not an expert, but I guess it's because the expected type is **TextInputProps** and it should be **TextInput**:
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/e3252aaa-ee3a-41c1-a611-d2efe2b3757e)


Similar problems with ScrollView component, **scrollToEnd()**, **scrollTo()**, and others are beeping.

Thanks in advance!

**Comment by aahahocevar** [comment] 2024-03-15 07:07
> Hi Everyone, The issue is fixed in latest version of `@gluestack-style/react` and `@gluestack-ui/themed`. Let me know if that works for you.

Hello everyone,

I just tried in an InputField component, no more problem here:
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/20a2feb9-6ed4-4ade-8a36-f0e89f6097d1)

But the functions **isFocused()**, **blur()**, **focus()** and others are beeping :)
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/86900f58-9e40-471f-af6c-3786c66bec3d)

I'm not an expert, but I guess it's because the expected type is **TextInputProps** and it should be **TextInput**:
![image](https://github.com/gluestack/gluestack-ui/assets/2762732/e3252aaa-ee3a-41c1-a611-d2efe2b3757e)


Similar problems with ScrollView component, **scrollToEnd()**, **scrollTo()**, and others are beeping.

Thanks in advance!

**Comment by antoinerochat** [comment] 2024-03-25 16:17
> Hi Everyone, The issue is fixed in latest version of `@gluestack-style/react` and `@gluestack-ui/themed`. Let me know if that works for you.

Hi @ankit-tailor, I think it's not working anymore since @gluestack-ui/themed version 1.1.16

**Comment by hwildwood** [comment] 2024-03-29 17:44
I'm experiencing the same issue.  I think the expected ref should be `RefObject<TextInput>` not `RefObject<TextInputProps>`?
