### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `variants` supplied to `Text`.

### ISSUE THREAD

**Issue by mduthilleul** [gluestack/gluestack-ui#1595] opened 2024-01-10 12:25 UTC
### Description

Warning: Failed prop type: Invalid props.style key `variants` supplied to `Text`.

### Steps to reproduce

1. Define variants for Text component
2. Add a text component
4. See the warning
```
Warning: Failed prop type: Invalid props.style key `variants` supplied to `Text`.
Bad object: {
  "color": "#000000",
  "fontFamily": "Poppins",
  "fontSize": 16,
  "fontWeight": 400,
  "variants": {
    "variant": {
      "h1": {
        "fontFamily": "PlayfairDisplay",
        "fontWeight": 400
      },
      ....
}
Valid keys: [
  "alignContent",
  "alignItems",
  "alignSelf",
  ...
]
    at Text (http://localhost:8081/index.bundle//&platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true)
    in Text (created by StyledText)
    in StyledComponent (created by RootNavigator)
    in RCTView (created by View)
    in View (created by View)
    in View (created by StyledVStack)
    in StyledComponent (created by RootNavigator)
    in RCTSafeAreaView (created by RootNavigator)
    in RootNavigator (created by App)
    in StorageContext (created by App)
    in DebugContext (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in ToastProvider (created by NativeBaseProvider)
    in PortalProvider (created by NativeBaseProvider)
    in HybridProvider (created by NativeBaseProvider)
    in ResponsiveQueryProvider (created by NativeBaseProvider)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by NativeBaseProvider)
    in NativeBaseConfigProviderProvider (created by NativeBaseProvider)
    in NativeBaseProvider (created by App)
    in ToastProvider (created by GluestackUIProvider)
    in PortalProvider (created by GluestackUIProvider)
    in StyledProvider (created by GluestackUIStyledProvider)
    in GluestackUIStyledProvider (created by GluestackUIProvider)
    in GluestackUIProvider (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```

### gluestack-ui Version

1.0.34

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [X] iOS

### Additional Information

This does not produces with version 1.0.25

**Comment by ankit-tailor** [comment] 2024-01-16 18:28
Hey @mduthilleul, The issue is fixed in the latest version. Please upgrade `@gluestack-style/react` and `@gluestack-ui/themed` to latest version. Closing the issue for now. Feel free to re-open in case you face any issues.

**Closed by ankit-tailor** 2024-01-16 18:28 UTC
Labels: bug
