### ISSUE TITLE
Issue while trying to make a reusable styled component

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1535] opened 2023-12-18 07:40 UTC
### Description

austin — 16/12/2023 05:23 Hey all, unsure if this is a bug but figured I'd post it here.  I am trying to make a reusable styled component using gluestack-ui/themed as a base  import { Button, ButtonIcon, styled } from '@gluestack-ui/themed';  ...Component here  const HeaderButton = styled(Button, {   px: 0,   w: '$10',   h: '$10',   rounded: '$full',   bg: '$backgroundDark800', });  return (   <HeaderButton>     <HeaderIcon as={AddIcon} />   </HeaderButton> )   The styles apply on native, but not on web for some reason.  The web button just renders with the default button style.

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by ankit-tailor** [comment] 2024-01-16 12:13
`gluestack-ui/themed` components are unstyled by default. To get styled components we have exported a config through `@gluestack-ui/config` package. 

When you create a styled component and pass styles to it like below,

```js
const Box = styled(View, {
 bg: '$red500',
 p: '$10'
});
```

Above styles will be injected in `gs-injected-boot-base-*` style block.

When you pass styles as extended theme like below,

```jsx
const App = () => {
  const config = {
    aliases: {},
    tokens: {},
    components: {
      Box: {
        theme: {
          bg: '$pink500',
          p: '$4',
        },
      },
    },
  };
  const ComposedBox = styled(
    Box,
    {
      bg: '$red500',
      p: '$10',
    },
    {
      componentName: 'ComposedBox',
    }
  );
  return (
    <GluestackUIProvider config={config}>
      <ComposedBox />
    </GluestackUIProvider>
  );
};
```

In above case styles will be injected in `gs-injected-extended-*` style block.

According to specificity, `boot-base` blocks are injected above the `gs-injected-extended`. That's why you are not able to override the styles when you compose the component which has extended theme.

To fix this you can define the extended theme for you extended component. That way it will work as intended. 

```jsx
const App = () => {
  const config = {
    aliases: {},
    tokens: {},
    components: {
      Box: {
        theme: {
          bg: '$pink500',
          p: '$4',
        },
      },
      ComposedBox: {
        theme: {
          bg: '$red500',
          p: '$10',
        },
      },
    },
  };
  const ComposedBox = styled(
    Box,
    {},
    {
      componentName: 'ComposedBox',
    }
  );
  return (
    <GluestackUIProvider config={config}>
      <ComposedBox />
    </GluestackUIProvider>
  );
};
```

Also to mention, we are working on this is issue. We'll fix this in future. Till then you can use the above approach to override the styles.

**Closed** 2024-01-24 06:43 UTC
Labels: bug, gluestack-style
