### ISSUE TITLE
Typo in paths on storybook examples when adding components

### ISSUE THREAD

**Issue by KannarFr** [gluestack/gluestack-ui#250] opened 2023-04-10 10:01 UTC
Just retried https://github.com/gluestack/ui/issues/240.

On step 3 of https://ui.gluestack.io/docs/getting-started/install-expo.

```bash
npx gluestack-ui@latest add button
```

Which throws 

```bash
➜ npx gluestack-ui@latest add button                                               
 
gluestack-ui is already initialised in your project! 
/ Pulling changes...  
Changes pulled successful. 
pull4ed changes
Error: ENOENT: no such file or directory, open '/home/kannar/.gluestack/cache/gluestack-ui/example/storybook/src/ui-components/button/config.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at /home/kannar/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/index.js:119:14
    at Array.map (<anonymous>)
    at /home/kannar/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/index.js:115:37
    at Array.map (<anonymous>)
    at copyFolders (/home/kannar/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/index.js:105:37)
    at componentAdder (/home/kannar/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/index.js:184:11)
    at async main (/home/kannar/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/index.js:20:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/kannar/.gluestack/cache/gluestack-ui/example/storybook/src/ui-components/button/config.json'
}
```

Because the folders in `/home/kannar/.gluestack/cache/gluestack-ui/example/storybook/src/ui-components` are all named with first character in upper case. 

So when I use `npx gluestack-ui@latest add Button` it works.

@vidhi499 I do not need any repository to produce it, just following the documentation and (not sure it's relevant here my OS is Exherbo (.org)).

**Comment by ankit-tailor** [comment] 2023-04-12 06:58
Hi @KannarFr, Thanks for reporting the issue. We will looking into it.

**Comment by mayank-96** [comment] 2023-04-20 11:37
Hey @KannarFr, this issue has been fixed with the latest version of `gluestack-ui`. I am closing this issue for now. Please feel free to reopen it if you face this problem again. Thank you!

**Closed by mayank-96** 2023-04-20 11:37 UTC

**Comment by IgnisDa** [comment] 2023-06-27 07:39
@mayank-96 I am getting this problem for some components. It works for buttons, but not for hstack and vstack.
![image](https://github.com/gluestack/gluestack-ui/assets/60938164/00f75168-93b5-4198-a1de-12d40cbac34e)

**Comment by IgnisDa** [comment] 2023-06-27 07:41
The problem is the file is named `HStack` but the cli is trying  to find `Hstack`. Same with `VStack`.
