### ISSUE TITLE
Failed prop type: Invalid prop `placeholderTextColor` supplied to `TextInput`: var(--colors-textLight500)

### ISSUE THREAD

**Issue by JJosephttg** [gluestack/gluestack-ui#1630] opened 2024-01-13 16:25 UTC
### Description

@gluestack-style/react 1.0.32 introduced a regression

### Steps to reproduce

See https://github.com/gluestack/gluestack-ui/issues/829

### gluestack-ui Version

@glustack-ui/themed: 1.0.35, @gluestack-ui/config: 1.0.11, @gluestack-style/react: 1.0.38

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

Unsure about iOS but I noticed on Android

**Comment by ankit-tailor** [comment] 2024-01-15 05:31
Hey @JJosephttg, Thanks for reporting the issue. We'll look into it.

**Comment by ankit-tailor** [comment] 2024-01-15 09:53
Hey @JJosephttg, The issue is fixed in latest version.

**Closed by ankit-tailor** 2024-01-15 09:53 UTC
Labels: bug
