### ISSUE TITLE
SelectIcon typescript error using "mr=$3"

### ISSUE THREAD

**Issue by faorte** [gluestack/gluestack-ui#1454] opened 2023-12-06 11:42 UTC
### Description

In documentation for Select component the example for SelectIcon shows using prop mr=$3 but this generates a typescript error

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.8

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

![Screenshot 2023-12-06 at 12 41 27](https://github.com/gluestack/gluestack-ui/assets/153067624/ad3b502a-fcab-4b80-bc98-cdf07f926c00)
![Screenshot 2023-12-06 at 12 41 51](https://github.com/gluestack/gluestack-ui/assets/153067624/9f9794fb-c948-4577-ac0c-83c21d5e8719)

**Comment by faorte** [comment] 2023-12-08 11:30
I am using     "@gluestack-style/react": "^1.0.26",
    "@gluestack-ui/config": "^1.0.8",
    "@gluestack-ui/themed": "^1.0.24",

**Comment by StanislavDalinin** [comment] 2023-12-10 21:57
Hello there, I've probably got the same issue, but a clearer type description.
The problem is not in the "mr=$3" property but in the child. The type error tells us that the SelectIcon doesn't allow any children.

<img width="1227" alt="Screenshot 2023-12-10 at 22 54 03" src="https://github.com/gluestack/gluestack-ui/assets/82456169/3cbc5a5b-6357-42d9-9af3-6be64de73b9a">

**Comment by ankit-tailor** [comment] 2024-01-29 09:54
Hey @faorte, The issue is fixed in the latest versions of `@gluestack-style/react` and `@gluestack-ui/themed`. Let me know if you face any issues.

**Closed by ankit-tailor** 2024-01-29 09:54 UTC
Labels: bug
