### ISSUE TITLE
Toast should render on top

### ISSUE THREAD

**Issue by thgh** [gluestack/gluestack-ui#433] opened 2023-05-10 20:08 UTC
### Description

Toast messages are hidden behind tabs

### Steps to reproduce

1. Go to https://ui.gluestack.io/docs/components/feedback/toast
2. Click on Press me several times
3. See this:
<img width="548" alt="Screenshot 2023-05-10 at 22 07 03" src="https://github.com/gluestack/gluestack-ui/assets/1109982/22be9ee3-cd72-4dc0-9460-995deb272919">

### gluestack-ui Version

website

### Platform

- [ ] Android
- [ ] Expo
- [ ] iOS
- [X] Next

### Additional Information

Also, clicking the toast quickly 3 times in a row only triggers 1 toast message.

**Comment by mayank-96** [comment] 2023-05-11 06:31
Hi @thgh , thank you for bringing this to our attention. We are aware of the issue you mentioned, and it is caused by having multiple providers. It will be fixed soon.

**Comment by Viraj-10** [comment] 2023-06-15 12:34
Hey @thgh, This issue has been now. Thanks for reporting.

**Closed by Viraj-10** 2023-06-15 12:34 UTC
Labels: bug
