### ISSUE TITLE
Styles are not injected for NextJs during production build 

### ISSUE THREAD

**Issue by topseySuave** [gluestack/gluestack-ui#1403] opened 2023-11-22 23:36 UTC
### Description
After running `npm run build`  and `npm run start` there is no styling for the elements even though the buttons and text elements work as they should. 
Gluestack styles are not injected into the website for NextJs during the production build 

### Steps to reproduce

Nothing special was done... It's a new app and it's the first time trying to build it for production. Not sure what else to do with this issue... Please if anyone has a solution for this, it would be greatly appreciated. 

**package.json**
```
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
"dependencies": {
    "@expo/html-elements": "latest",
    "@gluestack-style/react": "latest",
    "@gluestack-ui/config": "latest",
    "@gluestack-ui/overlay": "^0.1.12",
    "@gluestack-ui/themed": "latest",
    "@gluestack-ui/toast": "^0.1.20",
    "@gluestack/ui-next-adapter": "latest",
    "@legendapp/motion": "latest",
    "next": "^13.5.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native-svg": "13.4.0",
    "react-native-web": "^0.19.7",
    "react-native-web-linear-gradient": "^1.1.2",
 }
```

`next.config.js`
```
/** @type {import('next').NextConfig} */
const { withGluestackUI } = require('@gluestack/ui-next-adapter');

const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@gluestack-ui/themed"],
  assetPrefix: '/rake',
  rewrites: () => {
    return [
      { source: '/rake/_next/:path*', destination: '/_next/:path*' }
    ]
  },
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(ogg|mp3|wav|mpe?g)$/i,
      exclude: config.exclude,
      use: [
        {
          loader: require.resolve('url-loader'),
          options: {
            limit: config.inlineImageLimit,
            fallback: require.resolve('file-loader'),
            publicPath: `${config.assetPrefix}/_next/static/sound/`,
            outputPath: `/_next/static/sound/`,
            name: '[name]-[hash].[ext]',
            esModule: config.esModule || false,
          },
        },
      ],
    });

    return config;
  },
};

module.exports = withGluestackUI(nextConfig);
```

`/app/layout.tsx`
```

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className="gs">
      <MetaTags metadata={metadata} />

      <body className={leagueSpartan.className}>
        <Providers>
          <StyledJsxRegistry>{children}</StyledJsxRegistry>
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;
```

`Providers.tsx`

```
"use client";
import { OverlayProvider } from "@gluestack-ui/overlay";
import { config } from "../config/gluestack-ui.config";
import { GluestackUIProvider } from "@gluestack-ui/themed";
import { ToastProvider } from "@gluestack-ui/toast";
import { AppProvider } from "@/store/AppContext";

const Providers = ({ children }: { children: React.ReactNode }) => {
  return (
    <GluestackUIProvider config={config}>
      <OverlayProvider>
        <AppProvider>
            <ToastProvider>{children}</ToastProvider>
        </AppProvider>
      </OverlayProvider>
    </GluestackUIProvider>
  );
};

export default Providers;
```

`StlyeJsxRegistry.tsx`

```
"use client";

import React, { useRef, useState } from "react";
import { useServerInsertedHTML } from "next/navigation";
import { StyleRegistry, createStyleRegistry } from "styled-jsx";
import { Main } from "next/document";
// @ts-ignore
import { AppRegistry } from "react-native-web";
import { flush } from "@gluestack-ui/themed";

const StyledJsxRegistry = ({ children }: { children: React.ReactNode }) => {
  // Only create stylesheet once with lazy initial state
  // x-ref: https://reactjs.org/docs/hooks-reference.html#lazy-initial-state
  const [jsxStyleRegistry] = useState(() => createStyleRegistry());
  const isServerInserted = useRef(false);

  useServerInsertedHTML(() => {
    AppRegistry.registerComponent("RakeApp", () => Main);
    const { getStyleElement } = AppRegistry.getApplication("RakeApp");
    if (!isServerInserted.current) {
      isServerInserted.current = true;
      const styles = [getStyleElement(), jsxStyleRegistry.styles(), ...flush()];
      jsxStyleRegistry.flush();
      return <>{styles}</>;
    }
  });

  return <StyleRegistry registry={jsxStyleRegistry}>{children}</StyleRegistry>;
};

export default StyledJsxRegistry;
```

Not sure what 

### gluestack-ui Version

"@gluestack-ui/themed"="latest"

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Additional Information

It works fine for development, but it's another case when running `npm run build` on a NextJs web app.

**Comment by makkarMeenu** [comment] 2023-11-23 10:18
Hey @topseySuave , the issue you are facing is strange. This should not happen.
We created a next project and tried to build and even deployed on vercel to test the same. It is working fine for us.

Here is the website link:  [link](https://prod-build-gluestack.vercel.app/)
Repo link: [link](https://github.com/makkarMeenu/prod-build-gluestack)

Can you please help us further  by providing repo access or creating a similar minimal errror producing repository for the production of the issue?

**Comment by topseySuave** [comment] 2023-11-23 11:16
Hi @makkarMeenu thanks for responding, this is my deployment and what I can see, 

<img width="1652" alt="Screenshot 2023-11-23 at 12 15 45 PM" src="https://github.com/gluestack/gluestack-ui/assets/26353008/14d9649a-b208-45da-b9a1-2cb55c25f2a7">

**Comment by makkarMeenu** [comment] 2023-11-23 11:28
@topseySuave Please share the repository to help us further reproducing the issue. I won't be able to determine the issue from the snapshot of the build ui.

**Comment by topseySuave** [comment] 2023-11-23 11:54
Here it is @makkarMeenu https://github.com/topseySuave/rake-test

**Comment by topseySuave** [comment] 2023-11-23 12:27
Please @makkarMeenu confirm you got it.

**Comment by topseySuave** [comment] 2023-11-23 13:36
I noticed during development (`npm run dev`) that the element shown in the image was present, that holds all `gs` styling, but on prod build `npm run build` and `npm run start`. 
it's not in the head or body tag.

<img width="494" alt="Screenshot 2023-11-23 at 2 33 00 PM" src="https://github.com/gluestack/gluestack-ui/assets/26353008/2547ba2d-3e6c-44a7-9a4d-a7987431afe4">

**Comment by makkarMeenu** [comment] 2023-11-24 05:54
I have debugged your application and I could find out that for some reason, styles are not getting injected when I attach 
`RTCContextProvider`  .
Styles work fine in the build without `RTCContextProvider`.
```
"use client";
import { OverlayProvider } from "@gluestack-ui/overlay";
import { config } from "../config/gluestack-ui.config";
import { Button, ButtonText, GluestackUIProvider } from "@gluestack-ui/themed";
import { ToastProvider } from "@gluestack-ui/toast";
import RTCContextProvider from "@/store/RTCContext";
import { AppProvider } from "@/store/AppContext";

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <GluestackUIProvider config={config}>
      <OverlayProvider>
        <AppProvider>
          {/* <RTCContextProvider> */}
          <ToastProvider>
            <Button>
              <ButtonText>hello</ButtonText>
            </Button>
          </ToastProvider>
          {/* </RTCContextProvider> */}
        </AppProvider>
      </OverlayProvider>
    </GluestackUIProvider>
  );
}

export default Providers;
```


Although, I am trying to come up with the exact issue. Please allow me some time.

**Comment by makkarMeenu** [comment] 2023-11-24 08:48
Hi @topseySuave 
After debugging for hours, I found this issue https://github.com/vercel/next.js/issues/48335 . While using `useSearchParams` styles are not being injected from `registry.tsx`. 

You can wrap the entire application with `<Suspense> </Suspense>` to make the styles working in the build but this will break your SSR.
```
"use client";
import { OverlayProvider } from "@gluestack-ui/overlay";
import { config } from "../config/gluestack-ui.config";
import { GluestackUIProvider } from "@gluestack-ui/themed";
import { ToastProvider } from "@gluestack-ui/toast";
import RTCContextProvider from "@/store/RTCContext";
import { AppProvider } from "@/store/AppContext";
import { Suspense } from "react";

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <GluestackUIProvider config={config}>
      <OverlayProvider>
        <AppProvider>
          <Suspense>
            <RTCContextProvider>
              <ToastProvider>{children}</ToastProvider>
            </RTCContextProvider>
          </Suspense>
        </AppProvider>
      </OverlayProvider>
    </GluestackUIProvider>
  );
}

export default Providers;

```

If you need more help, we can discuss.

**Comment by topseySuave** [comment] 2023-11-24 08:51
Thank you so much for the time, but why is that hook causing the problem do you have any idea why?

**Comment by topseySuave** [comment] 2023-11-24 08:52
Ok I and finding out on the vercel link

**Comment by topseySuave** [comment] 2023-11-24 09:00
One question @makkarMeenu you said it will affect ssr? How do you mean? How will it?

**Comment by makkarMeenu** [comment] 2023-11-27 07:51
All the components wrapped inside `Suspense` will be client side rendered. You can see by doing view page source. 
I am closing this issue since it is nextjs. Can you please raise the same in next.js ?

**Closed by makkarMeenu** 2023-11-27 07:51 UTC
Labels: bug, gluestack-style
