### ISSUE TITLE
The `style` prop expects a mapping from style properties to values, not a string.

### ISSUE THREAD

**Issue by OneHatRepo** [gluestack/gluestack-ui#2513] opened 2024-10-11 00:26 UTC
### Description

Minimal app won't load, but gives error about style prop

### CodeSandbox/Snack link

https://github.com/OneHatRepo/Gluestack-Error

### Steps to reproduce

npm install
npm run web

see the error

### gluestack-ui Version

v2

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

### Additional Information

I stripped this down to the bare minimal example. How can I get Gluestack to load, so I can try it out?

<img width="1139" alt="Screenshot 2024-10-10 at 5 16 26 PM" src="https://github.com/user-attachments/assets/b0495b6c-6f33-45e0-b950-0bdad296e5e7">

**Comment by sra1kumar-NULL** [comment] 2024-10-18 07:49
Hey @OneHatRepo ,
I've checked the repository provided  and found out the issue is due to your babel.config file. I've commented out these plugins in the file and app started working fine.
Closing this issue for now. Please feel free to reopen this if you have any more queries.
```
module.exports = function(api) {
	api.cache(true);
	return {
		presets: [["babel-preset-expo", {
            jsxImportSource: "nativewind"
        }], "nativewind/babel"],
		plugins: [
            // 'react-native-classname-to-style',
            // ['react-native-platform-specific-extensions', { extensions: ['css', 'pcss'] }],
            // '@babel/plugin-transform-class-properties',
            // '@babel/plugin-transform-export-namespace-from',
            // '@babel/plugin-transform-runtime',
            // require.resolve('expo-router/babel'),
            'react-native-reanimated/plugin',
            ["module-resolver", {
                root: ["./"],
                alias: {
                    "@/": "./"
                }
            }]
        ],
		// sourceType: "unambiguous",
	};
};

```

**Closed by sra1kumar-NULL** 2024-10-18 07:49 UTC
Labels: bug
