### ISSUE TITLE
Build fail on expo 50

### ISSUE THREAD

**Issue by Axolem** [gluestack/gluestack-ui#1673] opened 2024-01-21 22:29 UTC
### Description

Expo Dev build fails when using expo-linear-gradient@12.3.0 on a project using expo@50.x.x when rolled back to expo@49.x.x the build succeeds. I think it's because @gluestack-ui/linear-gradient depends on expo-linear-gradient@12.3.0. I expect to use expo@50.x.x, @gluestack-ui@latest and build my project successfully

### Steps to reproduce

```
    "@gluestack-style/react": "^1.0.41",
    "@gluestack-ui/config": "^1.0.13",
    "@gluestack-ui/themed": "^1.0.37",
```

1. create new expo project with expo@50.x.x
2. Install latest gluestack-ui
3. Do a dev build `npx expo run:android`

### gluestack-ui Version

1.0.37

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

I inspected my package-lock.json and I found that is only this package depending on this version of expo-linear-gradient (12.3.0) 

```js
 "node_modules/@gluestack-ui/linear-gradient": {
      "version": "0.1.2",
      "resolved": "https://registry.npmjs.org/@gluestack-ui/linear-gradient/-/linear-gradient-0.1.2.tgz",
      "integrity": "sha512-bdZ8Y38odGJm0gYd...pBjRw==",
      "dependencies": {
        "expo-linear-gradient": "12.3.0" //Recent version(12.7.0) builds successfully
      },
      "peerDependencies": {
        "react": ">=16",
        "react-dom": ">=16"
      }
    },
```

### Here are the console errors

Using expo modules
  - expo-application (5.8.3)
  - expo-av (13.10.3)
  - expo-clipboard (5.0.1)
  - expo-constants (15.4.5)
  - expo-crypto (12.8.0)
  - expo-document-picker (11.10.1)
  - expo-eas-client (0.11.2)
  - expo-file-system (16.0.4)
  - expo-font (11.10.2)
  - expo-image-loader (4.6.0)
  - expo-image-picker (14.7.1)
  - expo-json-utils (0.12.3)
  - expo-keep-awake (12.8.2)
  - expo-linear-gradient (12.3.0)
  - expo-location (16.5.2)
  - expo-manifests (0.13.2)
  - expo-modules-core (1.11.7)G [48s]
  - expo-modules-core$android-annotation (1.11.7)
  - expo-modules-core$android-annotation-processor (1.11.7)
  - expo-permissions (14.2.1)
  - expo-secure-store (12.8.1)
  - expo-splash-screen (0.26.3)
  - expo-structured-headers (3.7.2)
  - expo-system-ui (2.9.3)
  - expo-updates (0.24.8)
  - expo-video-thumbnails (7.9.0)
  - expo-web-browser (12.8.1)

> Task :expo-linear-gradient:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-linear-gradient:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 7s
394 actionable tasks: 8 executed, 386 up-to-date

**Comment by rennanlurahy** [comment] 2024-01-22 23:45
I had the same issue. I had to install the correct version of expo-linear-gradient manually in my project with "npx expo install expo-linear-gradient".

**Comment by j10ra** [comment] 2024-01-25 02:08
> I had the same issue. I had to install the correct version of expo-linear-gradient manually in my project with "npx expo install expo-linear-gradient".

this solved my build issue.

However,  I'm experiencing where using an icon produces a render error.. For example:
`<Icon as={AddIcon} m="$2" w="$4" h="$4" />`

this also happens when you try to use
`<ButtonIcon as={AddIcon} mr="$2" />`

![image](https://github.com/gluestack/gluestack-ui/assets/3077983/f3916281-4cc7-443a-8604-a2f3c2313809)

![image](https://github.com/gluestack/gluestack-ui/assets/3077983/6c11e4eb-af3f-490c-8998-10489d7aee50)

**Comment by j10ra** [comment] 2024-01-25 02:20
> > I had the same issue. I had to install the correct version of expo-linear-gradient manually in my project with "npx expo install expo-linear-gradient".
> 
> this solved my build issue.
> 
> However, I'm experiencing where using an icon produces a render error.. For example: `<Icon as={AddIcon} m="$2" w="$4" h="$4" />`
> 
> this also happens when you try to use `<ButtonIcon as={AddIcon} mr="$2" />`
> 
> ![image](https://private-user-images.githubusercontent.com/3077983/299514335-f3916281-4cc7-443a-8604-a2f3c2313809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDg5NTcsIm5iZiI6MTcwNjE0ODY1NywicGF0aCI6Ii8zMDc3OTgzLzI5OTUxNDMzNS1mMzkxNjI4MS00Y2M3LTQ0M2EtODYwNC1hMmYzYzIzMTM4MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDIxMDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAxMzYyOTY4YzQ4ZWU5MjFlMTQ0MzVjMzYxNWJjOWE5N2JiOTQ0YTUxY2UyZDZmZTk2N2NkZjA0ZjAwNWI1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HLsJqdEZzcTyVXD9VcKM_q7x65eB4t9pCyRo_tqJwZU)
> 
> ![image](https://private-user-images.githubusercontent.com/3077983/299514099-6c11e4eb-af3f-490c-8998-10489d7aee50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDg5NTcsIm5iZiI6MTcwNjE0ODY1NywicGF0aCI6Ii8zMDc3OTgzLzI5OTUxNDA5OS02YzExZTRlYi1hZjNmLTQ5MGMtODk5OC0xMDQ4OWQ3YWVlNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDIxMDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjMwNmVhYjc3NzE3Y2Q0Y2VmY2FkOGQyMzVkNDc2NzgzNWYxOGI2ZjYyNTBlYmNhZWU0OTk3ZjBlODAwY2I1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y6LQY39qgMOAmJnQRDs5xpZoCBn1zwfCisCQ6lJGc2c)

Apparently I solved it by
npm install react-native-svg
npm install react-native-svg-transformer

found it from [here](https://stackoverflow.com/questions/53326897/invariant-violation-requirenativecomponent-rnsvgpath-was-not-found-in-the-ui)

**Comment by timmyjose** [comment] 2024-01-25 04:53
> I had the same issue. I had to install the correct version of expo-linear-gradient manually in my project with "npx expo install expo-linear-gradient".

Strange. I tried doing the same, and the exact same build issue was solved, but then the expo app (only Android) got stuck at the splash screen. Maybe I'll try the other suggestions in here as well.

**Comment by jeffrey-dot-li** [comment] 2024-01-26 15:31
the issue is with the version of expo-linear-gradient. Applying the following patch to the package json works for me:

```
diff --git a/CHANGELOG.md b/CHANGELOG.md
deleted file mode 100644
index c80a3c31b08eb853d9560984af736bf6a2309784..0000000000000000000000000000000000000000
diff --git a/package.json b/package.json
index 64cdfaa2de3958facd1057cb5d6e2330e39d4b42..f188c350b125dfdd6c6f1011d13347dede890639 100644
--- a/package.json
+++ b/package.json
@@ -43,7 +43,7 @@
     "typescript": "^4.7.4"
   },
   "dependencies": {
-    "expo-linear-gradient": "12.3.0"
+    "expo-linear-gradient": "12.7.0"
   },
   "peerDependencies": {
     "react": ">=16",
```

**Comment by jeffrey-dot-li** [comment] 2024-01-26 15:35
Fixed: https://github.com/gluestack/gluestack-ui/pull/1710

**Comment by rajat693** [comment] 2024-01-29 11:32
closing this issue, as the PR is merged and docs are updated

**Closed by rajat693** 2024-01-29 11:32 UTC
Labels: bug
