### ISSUE TITLE
Uncaught ReferenceError: require is not defined  at ./node_modules/@gluestack-ui/checkbox/node_modules/@react-stately/toggle/dist/import.mjs

### ISSUE THREAD

**Issue by elenitaex5** [gluestack/gluestack-ui#1277] opened 2023-10-13 11:02 UTC
### Description

I've only installed gluestack trying to start my migration from Native Base to Gluestack. After running my web server this error appears in console and only shows blank screen.

### Steps to reproduce

My project is running in EXPO SDK 49

1. Install gluestack in my project with
`npm i @gluestack-ui/themed @gluestack-style/react react-native-svg@13.4.0`

2. In my App.tsx include
```
import { config as gluestackConfig } from '@gluestack-ui/config'
import { GluestackUIProvider } from '@gluestack-ui/themed'

...
export const App = () => {
  const isLoadingComplete = useCachedResources()
  usePushNotifications()

  useEffect(() => {
    setupAxios()
  }, [])

  if (!isLoadingComplete) {
    return null
  } else {
    return (
      <EventProvider>
        <GluestackUIProvider config={gluestackConfig}>
          <NativeBaseProvider theme={theme}>
            <I18nextProvider i18n={i18n}>
              <NavigationContainer linking={linking}>
                <UIProvider>
                  <AuthProvider>
                    <AppStackNavigation />
                    <StatusBar />
                  </AuthProvider>
                </UIProvider>
              </NavigationContainer>
            </I18nextProvider>
          </NativeBaseProvider>
        </GluestackUIProvider>
      </EventProvider>
    )
  }
}
```

I have also Native Base provider because is needed until migration is finished but has been even possible to start.

3. `npx expo start web`
4.  Shows the following error.

<img width="685" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/14013852/10861caf-8ba0-41ba-b939-8b2ff523b815">

### gluestack-ui Version

^1.0.4

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by akash3gtm** [comment] 2023-10-17 06:23
Hi @elenitaex5 
Could you please provide a code-sandbox or expo snack link.

**Comment by adamyodinsky** [comment] 2024-08-30 16:21
I have this issue as well

**Comment by Declan-Watts** [comment] 2024-09-13 08:16
I'm having this bug as well on an IOS build

**Comment by arkajyotiMukherjee** [comment] 2024-09-16 19:22
facing a similar problem with gluestacks v2 and expo app with gluestack init command
ReferenceError: require is not defined
    at file:///Users/<user>/Desktop/<project-name>/node_modules/@gluestack-ui/nativewind-utils/tailwind-plugin/index.js:1:16
    
   expo: 51.0.28
   react-native: 0.74.5
   npm: 10.8.2
   node: v22.7.0

**Comment by sharpcodes19wf** [comment] 2024-09-18 10:08
i am also having this issue.

**Comment by trannguyenvu3482** [comment] 2024-09-20 11:53
im having the same issue

**Comment by rajat693** [comment] 2024-09-23 06:34
Hi, we tried to debug this issue for Gluestack UI v2, but it seems to be working fine on our end. We kindly request you to share a GitHub repository or detailed steps to reproduce the issue so we can assist you further.

**Comment by sra1kumar-NULL** [comment] 2024-09-24 08:10
Hey @elenitaex5 , we are closing this issue for now, please feel free to reopen the issue if you are still facing it/ having any queries about it.

**Closed by sra1kumar-NULL** 2024-09-24 08:10 UTC
Labels: bug, waiting for response, nativebase-migration

**Comment by Declan-Watts** [comment] 2024-09-24 08:55
Hey there I did try this again today and it didn't work. I'll work on getting an example repository up with this issue happening
