### ISSUE TITLE
ForControl-Radio: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [gluestack/gluestack-ui#2393] opened 2024-08-20 21:10 UTC
### Description

says TypeError: Cannot read properties of undefined (reading '0') when checking one of the raido input in the radiogroup

### CodeSandbox/Snack link

https://gluestack.io/ui/docs/components/form-control

### Steps to reproduce

1. Go to 'https://gluestack.io/ui/docs/components/form-control' 
2. Click on any of the raido inputs in The Radio Component  
3. See error says (`TypeError: Cannot read properties of undefined (reading '0')
`)

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by rajat693** [comment] 2024-08-23 13:48
The issue is fixed so, I am closing it.
Thank You

**Closed by rajat693** 2024-08-23 13:48 UTC
Labels: bug
