### ISSUE TITLE
Icon size can't be customized 

### ISSUE THREAD

**Issue by LipLoody** [gluestack/gluestack-ui#1662] opened 2024-01-17 20:59 UTC
### Description

Icon size can't be customized 

### Steps to reproduce

With this config: gluestack-ui.config.ts
```
import { config as defaultConfig } from '@gluestack-ui/config';
import { createConfig } from '@gluestack-ui/themed';

const config = createConfig({
  ...defaultConfig,
  components: {
    ...defaultConfig.components,
    Icon: {
      theme: {
        defaultProps: {
          size: 'md',
        },
        variants: {
          size: {
            xs: {
              w: '$4',
              h: '$4',
              props: {
                size: 12,
              },
            },
            sm: {
              w: '$4',
              h: '$4',
              props: {
                size: 16,
              },
            },
            md: {
              w: '$6',
              h: '$6',
              props: {
                size: 24,
              },
            },
            lg: {
              w: '$7',
              h: '$7',
              props: {
                size: 28,
              },
            },
            xl: {
              w: '$8',
              h: '$8',
              props: {
                size: 32,
              },
            },
            '2xl': {
              w: '$9',
              h: '$9',
              props: {
                size: 36,
              },
            },
          },
        },
      },
    },
  },
} as const);

export { config };

// Get the type of Config
type ConfigType = typeof config;

type Components = typeof defaultConfig.components;
// Extend the internal styled config
declare module '@gluestack-style/react' {
  interface ICustomConfig extends ConfigType {}
  interface ICustomComponents extends Components {}
}
```

Any size prop is not overriding the default Icon size:
app.js
```
import { Ionicons } from '@expo/vector-icons';
import { GluestackUIProvider, Icon, VStack } from '@gluestack-ui/themed';

import { config } from './gluestack-ui.config';

export default function App() {
  return (
    <GluestackUIProvider config={config}>
      <VStack space={'md'}>
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'xs'} />
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'sm'} />
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'md'} />
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'lg'} />
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'xl'} />
        <Icon as={Ionicons} name={'chevron-forward-outline'} size={'2xl'} />
      </VStack>
    </GluestackUIProvider>
  );
}
```

### gluestack-ui Version

1.0.34

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [X] Android
- [X] iOS

**Comment by rajat693** [comment] 2024-01-19 10:51
Step 1 : Eject Theme: Run following command to eject the theme. This will create a config folder
`npx gluestack-ui-scripts eject-theme`

Step 2 : Update Tokens: you can find all of your components theme inside **config/theme** folder. you can find theme file for each component. 

Step 3 : Apply Config: Apply the config to the **GluestackUIProvider**.

for more info please refer the docs : https://gluestack.io/ui/docs/theme-configuration/customizing-theme

**Comment by LipLoody** [comment] 2024-01-20 00:19
Thanks a lot @rajat693
feel free to close it

**Comment by rajat693** [comment] 2024-01-22 06:47
So, as the issue is resolved, I am closing it.

**Closed by rajat693** 2024-01-22 06:47 UTC
Labels: bug
