### ISSUE TITLE
@gluestack-style/react 1.0.28, android app crashed.

### ISSUE THREAD

**Issue by vilenleung** [gluestack/gluestack-ui#1499] opened 2023-12-14 06:14 UTC
### Description

Broken my App.

### Steps to reproduce

 ERROR  Warning: Failed prop type: Invalid prop `size` of type `string` supplied to `Icon`, expected `number`.
Warning: Failed prop type: Invalid prop `fontSize` of type `string` supplied to `Text`, expected `number`.

```
<Input variant='rounded' size='xl'>
    <InputSlot sx={{pl: '$3'}}>
        <InputIcon as={MaterialIcons} name='account-box' size='lg' />
     </InputSlot>
      <InputField />
</Input>
```

### gluestack-ui Version

1.0.25

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

**Comment by surajahmed** [comment] 2023-12-15 06:49
@vilenleung, Thanks for reporting this. We'll look into this.

**Comment by teckbeng-payboy** [comment] 2023-12-15 10:02
` "dependencies": {
    "@gluestack-style/react": "^1.0.29",
    "@gluestack-ui/config": "^1.0.9",
    "@gluestack-ui/themed": "^1.0.27",
    "lucide-react-native": "^0.295.0",
    "react": "18.2.0",
    "react-native": "0.73.0",
    "react-native-svg": "13.4.0"
  },`
  
  ` <GluestackUIProvider config={config}>
      <SafeAreaView>
        <Text>Hello World!</Text>
        <Icon as={Camera} size="md" />
      </SafeAreaView>
    </GluestackUIProvider>`
    
    i think is the same issue. i just created with fresh new project. and the icon doesnt work

**Comment by Viraj-10** [comment] 2023-12-15 11:01
Hey @teckbeng-payboy, Please upgrade to latest version of `@gluestack-ui/themed, @gluestack-ui/config & @gluestack-style/react`.

**Comment by teckbeng-payboy** [comment] 2023-12-15 11:58
@Viraj-10  just upgrade to latest version, the issue still exist

**Comment by Viraj-10** [comment] 2023-12-15 13:43
@teckbeng-payboy Thanks for reporting, We will have a look.

**Comment by conghai** [comment] 2023-12-20 03:16
Not official but I used it well with: fontSize (not size) & not crash on Android device

```
<Icon
    as={(pd: any) => <MaterialCommunityIcons name={item.icon} {...pd} />}
    fontSize="$md"
    color={active ? activeColor : textColor}
  />
```

**Comment by sang-au** [comment] 2023-12-21 13:26
let's upgrade to latest version, it was fixed

**Comment by ankit-tailor** [comment] 2023-12-22 05:41
Hello everyone, The issue is fixed in the latest version. Please upgrade to latest version.

**Closed by ankit-tailor** 2023-12-22 05:41 UTC
Labels: bug, gluestack-style
