### ISSUE TITLE
Using toast as useEffect dependency causes infinite calls.

### ISSUE THREAD

**Issue by endrits079** [gluestack/gluestack-ui#1940] opened 2024-03-13 12:04 UTC
### Description

toast causes useEffect to run infinitely if used as dependency, it apparently shouldn't do that

### Steps to reproduce

Inside a component

1. const toast = useToast()
2. useEffect(()=>{
  toast.show(...)
},[toast,error])

3. That's it

### gluestack-ui Version

1.1.8

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by surajahmed** [comment] 2024-03-15 09:46
@endrits079 Thanks for reporting this. We'll have a look.

**Comment by DaminiPandey** [comment] 2024-05-09 06:29
Hey @endrits079, this is an expected behaviour as useToast hook internally is accessing some context values.
Calling toast.show() inside the useEffect hook is somehow causing the toast context values to update, which then creates a new toast object.
Since you have added toast in the dependency array, useEffect sees a new toast object, re-runs, and calls toast.show again. This cycle repeats, causing the infinite loop.



For more clarity this is the code snippet for our useToast hook:

`  const useToast = () => {
    const {
      AnimationWrapper,
      AnimatePresence,
      setToast,
      hideAll,
      isActive,
      hideToast,
    } = React.useContext(ToastContext);
    AnimatePresence.current = StyledAnimatePresence;
    AnimationWrapper.current = StyledAnimationWrapper;
    const toast = useMemo(
      () => ({
        show: setToast,
        close: hideToast,
        closeAll: hideAll,
        isActive,
      }),
      [setToast, hideAll, isActive, hideToast]
    );

    return toast;
  };`
  
  A possible solution for this is to **empty the dependency array**. If you only want the toast to show once on initial render, change the useEffect dependency array to []. This prevents re-runs on subsequent changes to toast.

**Comment by sra1kumar-NULL** [comment] 2024-09-24 08:04
Hey @endrits079 , we are closing this issue for now, please feel free to reopen the issue if you are still facing it/ having any queries about it.

**Closed by sra1kumar-NULL** 2024-09-24 08:04 UTC
Labels: bug, waiting for response
