### ISSUE TITLE
in next app router using a Center before Heading leads to a hydration error

### ISSUE THREAD

**Issue by macrozone** [gluestack/gluestack-ui#1918] opened 2024-03-08 08:36 UTC
### Description

Using a Center, View or Box on your page before any Heading leads to a hydration error. More components may be affected

### CodeSandbox/Snack link

https://github.com/macrozone/gluestack-hydration-reproduction

### Steps to reproduce

best checkout the repo above https://github.com/macrozone/gluestack-hydration-reproduction

not sure whether this would work in a codesandbox, so i created a new nextjs app that shows the error

the reproduction is a freshly created nextjs app where gluestack is installed according to the guidelines https://gluestack.io/ui/docs/guides/install-nextjs

1. clone the repo
2. yarn install
3. yarn dev
4. goto localhost:3000
5. click the first link
6. reload the page --> hydration error

the bug only happens if Center is used _before_ any header. The same error happens with Box and View. I did not check other components

As a workaround, you can add a empty heading

### gluestack-ui Version

   "@gluestack-style/react": "^1.0.49",     "@gluestack-ui/config": "^1.1.16",     "@gluestack-ui/themed": "^1.1.9",     "@gluestack/ui-next-adapter": "^2.1.11",

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by surajahmed** [comment] 2024-03-12 11:43
@macrozone Thanks for reporting this. We'll have a look.

**Comment by JavanPoirier** [comment] 2024-03-21 05:28
@macrozone, thanks for the report. I encounter this months ago and couldn't find the cause and when back to page router. Confirmed this was indeed the case. +1 👀

**Comment by farmhutsoftwareteam** [comment] 2024-04-18 19:36
has anyone found a way to handle this , I mainly get it when using the text component, ended up using tailwind for texts.

NextJS 14 App Router

**Comment by sra1kumar-NULL** [comment] 2024-10-08 11:26
Closing this issue for now, feel free to reopen on any issue encounter or discussion.

**Closed by sra1kumar-NULL** 2024-10-08 11:26 UTC
Labels: bug
