### ISSUE TITLE
Customizing components Typescript errors

### ISSUE THREAD

**Issue by schmitzc** [gluestack/gluestack-ui#1113] opened 2023-09-15 20:58 UTC
### Description

When I create a custom theme to customize components, there are Typescript errors in the theme file.

### Steps to reproduce

1. Copy the example code to a Typescript file from the [Customizing Components doc](https://ui.gluestack.io/docs/theme/customizing-components)

```
// gluestack-ui.config.ts

import { createConfig, config as defaultConfig, } from '@gluestack-ui/themed';

   const config = createConfig({
   ...defaultConfig.theme,
   tokens: {
     ...defaultConfig.theme.tokens,
     colors: {
       ...defaultConfig.theme.tokens.colors,
       primary600_alpha_10: '#1a91ff1a',
       primary600_alpha_20: '#1a91ff33',
     },
   },

   components: {
     Button: {
       theme: {
         variants: {
           variant: {
             ghost: {
               'bg': 'transparent',
               '_text': {
                 color: '$primary600',
               },
               ':hover': {
                 _text: {
                   color: '$primary600',
                 },
                 bg: '$primary600_alpha_10',
               },
               ':active': {
                 _text: {
                   color: '$primary600',
                 },
                 bg: '$primary600_alpha_20',
               },
               '_dark': {
                 'bg': 'transparent',
                 '_text': {
                   color: '$primary600',
                 },
                 ':hover': {
                   _text: {
                     color: '$primary600',
                   },
                   bg: '$primary600_alpha_10',
                 },
                 ':active': {
                   _text: {
                     color: '$primary600',
                   },
                   bg: '$primary600_alpha_20',
                 },
               },
             },
           },
         },
       },
       componentConfig: {
         descendantStyle: ['_text'],
       },
     },
   },
 });

// Get the type of Config
type ConfigType = typeof config;

// Extend the internal ui config
declare module "@gluestack-ui/themed" {
  interface UIConfig extends ConfigType {}
}
```
2. Run `tsc`, and this is the output I receive:

```
> tsc --noEmit

lib/gluestack-ui/theme.ts:9:11 - error TS2322: Type '{ variant: string; }' is not assignable to type '(RNProps & RNStyledProps & GlobalVariantAliasesProps<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; ... 13 more ...; readonly rounded: "borderRadius"; }, { ...; }> & {}) | undefined'.
  Object literal may only specify known properties, and 'variant' does not exist in type 'RNProps & RNStyledProps & GlobalVariantAliasesProps<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; ... 13 more ...; readonly rounded: "borderRadius"; }, { ...; }> & {}'.

9           variant: 'ghost',
            ~~~~~~~

  ../node_modules/@gluestack-style/react/lib/typescript/types.d.ts:133:5
    133     props?: RNProps & RNStyledProps & GlobalVariantAliasesProps<Aliases, Tokens> & {
            ~~~~~
    The expected type comes from property 'props' which is declared here on type 'Partial<GlobalStyles<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; readonly px: "paddingHorizontal"; readonly py: "paddingVertical"; ... 11 more ...; readonly rounded: "borderRadius"; }, { ...; }, GlobalStyles<...> | undefined>>'

lib/gluestack-ui/theme.ts:15:15 - error TS2322: Type '{ backgroundColor: string; _text: { color: string; }; }' is not assignable to type 'Partial<GlobalVariantSx<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; readonly px: "paddingHorizontal"; readonly py: "paddingVertical"; ... 11 more ...; readonly rounded: "borderRadius"; }, { ...; }, unknown, ""> & { ...; }> |...'.
  Object literal may only specify known properties, and '_text' does not exist in type 'Partial<GlobalVariantSx<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; readonly px: "paddingHorizontal"; readonly py: "paddingVertical"; ... 11 more ...; readonly rounded: "borderRadius"; }, { ...; }, unknown, ""> & { ...; }>'.

15               _text: {
                 ~~~~~

  ../node_modules/@gluestack-style/react/lib/typescript/types.d.ts:153:25
    153     [Key: string & {}]: {
                                ~
    154         [Key in keyof Variants | (string & {})]?: Partial<GlobalVariantSx<AliasTypes, TokenTypes, Variants> & {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
    156         }>;
        ~~~~~~~~~~~
    157     };
        ~~~~~
    The expected type comes from property 'ghost' which is declared here on type '{ [x: string & {}]: Partial<GlobalVariantSx<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; readonly px: "paddingHorizontal"; ... 12 more ...; readonly rounded: "borderRadius"; }, { ...; }, unknown, ""> & { ...; }> | undefined; }'

lib/gluestack-ui/theme.ts:22:7 - error TS2739: Type '{ descendantStyle: string[]; }' is missing the following properties from type 'IConfigProps': ancestorStyle, resolveProps, componentName

22       componentConfig: {
         ~~~~~~~~~~~~~~~

  ../node_modules/@gluestack-style/react/lib/typescript/types.d.ts:73:13
    73             componentConfig?: IConfigProps;
                   ~~~~~~~~~~~~~~~
    The expected type comes from property 'componentConfig' which is declared here on type '{ theme: Partial<GlobalStyles<{ readonly bg: "backgroundColor"; readonly bgColor: "backgroundColor"; readonly h: "height"; readonly w: "width"; readonly p: "padding"; readonly px: "paddingHorizontal"; ... 12 more ...; readonly rounded: "borderRadius"; }, { ...; }, GlobalStyles<...> | undefined>>; componentConfig?: I...'
```

### gluestack-ui Version

0.1.44

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by ankit-tailor** [comment] 2023-09-20 06:56
Hey @schmitzc, The issue is fixed in the latest version. Let me know if it works for you.

**Closed by ankit-tailor** 2023-09-20 06:56 UTC
Labels: bug

**Comment by johnjensenish** [comment] 2023-09-28 20:46
I'm Cassie's colleague and the fix did appear to work.
