### ISSUE TITLE
disappear input placeholder after touching (without focus)

### ISSUE THREAD

**Issue by arsalannury** [gluestack/gluestack-ui#1381] opened 2023-11-13 20:30 UTC
### Description

after touching inputs the placeholder disappears and I have to type something and then remove it to show the placeholder again

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

1.0.15

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [ ] iOS

### Additional Information

`<Input
        variant="outline"
        size="md">
        <InputField
          placeholder={placehoderType === "inline" ? placehoder : ""}
          direction="rtl"
          writingDirection="rtl"
          fontFamily="Vazir"
          sx={{ _input: { fontFamily: "Vaizr" } }}
        />
      </Input>`

**Comment by makkarMeenu** [comment] 2023-11-15 06:28
Hey @arsalannury , I could not reproduce this issue. Can you please create a snack and share the error reproducible code.

https://github.com/gluestack/gluestack-ui/assets/54400869/a168607f-a61a-479e-91d7-03d95ad1876b

**Comment by arsalannury** [comment] 2023-11-15 09:46
screen record from my device (Xiaomi Redmi Note 12s)

https://github.com/gluestack/gluestack-ui/assets/82847525/9e0ceae5-e901-4ac3-8fd4-58efc3600cd9

**Comment by arsalannury** [comment] 2023-11-15 10:00
as you can see after I touched the inputs the placeholder disappeared so I must type into them and remove it to show the placeholder again

this is the screen record from my device Xiaomi Redmi Note 12 s


https://github.com/gluestack/gluestack-ui/assets/82847525/0959a433-0a2f-4e70-83d4-336517d7f16e

**Comment by makkarMeenu** [comment] 2023-11-15 11:39
Hi @arsalannury , I also checked in a real samsung device and could not reproduce this.  Can you please create a snack for the reproducible error, so that I can directly scan it. I think this issue is because of `placeholder={placehoderType === "inline" ? placehoder : ""} ` condition.

**Comment by arsalannury** [comment] 2023-11-15 19:10
I checked this `placeholder={placehoderType === "inline" ? placehoder : ""}` and **it was a problem** but I think it's not wrong because I can't change the placeholder type with touch during the run application so you may check this anytime you can

**Closed** 2023-11-15 19:10 UTC
Labels: bug
