### ISSUE TITLE
LucideIcon size doesn't support the "md", "lg" etc

### ISSUE THREAD

**Issue by Gluant101** [gluestack/gluestack-ui#1516] opened 2023-12-15 10:12 UTC
### Description

Beng — Today at 14:13 Suddenly all my LucideIcon size doesn't support the "md", "lg" etc.. it only accept number.. anyone know whats the issue here?

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

3.3.1

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

macorifice — Today at 15:29
the size should be a property of InputIcon

_No response_

**Comment by teckbeng-payboy** [comment] 2023-12-15 10:20
```
"dependencies": {
    "@gluestack-style/react": "^1.0.29",
    "@gluestack-ui/config": "^1.0.9",
    "@gluestack-ui/themed": "^1.0.27",
    "lucide-react-native": "^0.295.0",
    "react": "18.2.0",
    "react-native": "0.73.0",
    "react-native-svg": "13.4.0"
  },
```
 
  ```
 <GluestackUIProvider config={config}>
      <SafeAreaView>
        <Text>Hello World!</Text>
        <Icon as={Camera} size="md" />
      </SafeAreaView>
    </GluestackUIProvider>
```

here's the minimal code to reproduce the issue

**Comment by BooYeu** [comment] 2023-12-15 13:08
I update @gluestack-ui/themed from 1.0.26 to 1.0.29. All icons can't active

**Comment by pierrebiver** [comment] 2023-12-15 13:40
same issue here, only the icons coming from gluestack works.

**Comment by Viraj-10** [comment] 2023-12-15 13:42
Hey @pierrebiver @BooYeu @teckbeng-payboy, Thanks for reporting this issue. We will have a look.

**Comment by millerm30** [comment] 2023-12-15 18:55
I've updated to 1.0.29 for testing and having the same issue with ButtonIcon as one example.
"md" is not a valid dimension. Dimensions must be a number, "auto", or a string suffixed with "%".
"lg" is not a valid dimension. Dimensions must be a number, "auto", or a string suffixed with "%".

And when you try say size={20} I get 
Type 'number' is not assignable to type '"xs" | "sm" | "md" | "lg" | "xl" | "2xs" | undefined'.

What has worked for me in the short term is this.

<MaterialCommunityIcons name="linkedin" color="black" size={22} />

**Comment by sang-au** [comment] 2023-12-16 07:58
I have the same issue

**Comment by hocasiones** [comment] 2023-12-17 19:29
Same here

**Comment by teckbeng-payboy** [comment] 2023-12-20 03:08
@Gluant101  is there any possibilities to make this card urgent? cause its affecting all the people who implement this lucide icons.. even the user roll back to older version its still cant work. thanks

**Comment by BooYeu** [comment] 2023-12-20 03:12
You can try @gluestack-style/react @ 1.0.26. It is fine

**Comment by conghai** [comment] 2023-12-20 03:15
Not official but I used it well with: fontSize (not size) & not crash on Android device

```
<Icon
    as={(pd: any) => <MaterialCommunityIcons name={item.icon} {...pd} />}
    fontSize="$md"
    color={active ? activeColor : textColor}
  />
```

**Comment by teckbeng-payboy** [comment] 2023-12-20 03:22
> You can try @gluestack-style/react @ 1.0.26. It is fine

i tried this but still no luck
```
"@gluestack-style/react": "^1.0.26",
    "@gluestack-ui/config": "^1.0.8",
    "@gluestack-ui/themed": "^1.0.25",
    ```

**Comment by hocasiones** [comment] 2023-12-20 07:46
ok here's how I made it work for me. I tried implementing "@gluestack-style/react": "^1.0.26" as suggested above but didn't work so was I did was I tried first was removing ^ before the version number and see if it works for you.

If not, try implementing the following:

"@gluestack-style/react": "1.0.26",
"@gluestack-style/react": "1.0.16",

This one already worked for me but then I wanted the higher version of "@gluestack-style/react" so I tried increasing its version until I ended up to "latest" and it still work so go try it yourself.

Thank me later and credits to the one who suggest v1.0.26 above.

**Comment by Viraj-10** [comment] 2023-12-21 10:52
Hey All, Please update to latest version of `@gluestack-ui/style` version `1.0.30`.

**Comment by sang-au** [comment] 2023-12-21 11:38
Look seem this issue was fixed with the latest version

    "@gluestack-style/react": "1.0.30",
    "@gluestack-ui/config": "1.0.10",
    "@gluestack-ui/themed": "1.0.31",

**Comment by teckbeng-payboy** [comment] 2023-12-21 13:22
> Look seem this issue was fixed with the latest version
> 
> ```
> "@gluestack-style/react": "1.0.30",
> "@gluestack-ui/config": "1.0.10",
> "@gluestack-ui/themed": "1.0.31",
> ```

same, the issue is fixed in this version @Viraj-10

**Closed** 2023-12-22 11:36 UTC
Labels: bug, gluestack-style
