### ISSUE TITLE
Invalid prop `placeholderTextColor`

### ISSUE THREAD

**Issue by njt1982** [gluestack/gluestack-ui#1059] opened 2023-09-12 10:37 UTC
### Description

When using an `Input` / `InputField` with placeholder text, I'm getting a warning

### gluestack-ui Version

0.1.37

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

<img width="522" alt="image" src="https://github.com/gluestack/gluestack-ui/assets/384976/d2a8b370-bcc7-4982-9a56-a5e04a9fbcad">

```
Warning: Failed prop type: Invalid prop `placeholderTextColor` supplied to `TextInput`: $textLight500
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)
```

This was fine before I updated to 0.1.37 this morning (from 0.1.1).

    <Input variant="rounded" m={4} borderWidth={0} bg="$white">
      <InputIcon
        as={Icon}
        size={22}
        my="$2"
        ml="$4"
        name="search"
        color="$customGray100"
      />
      <InputField
        placeholder="Search"
        autoFocus={true}
        clearButtonMode="always"
        autoCapitalize="none"
        autoCorrect={false}
        value={this.state.searchQuery}
        onChangeText={text => this.setState({ searchQuery: text })}
      />
      {this._renderSearchSpinner()}
    </Input>

I'm not overriding this style or property anywhere, either... Although I do have a custom gluestack-ui.config.js - but I'm only overriding the icon colour:

    Input: {
      theme: {
        _icon: {
          color: '$customGray100',
        },
      },
    },

Any thoughts?

**Comment by makkarMeenu** [comment] 2023-09-12 10:39
This is a duplicate of  https://github.com/gluestack/gluestack-ui/issues/829. We are working on that one.

**Closed by makkarMeenu** 2023-09-12 10:39 UTC
Labels: bug

**Comment by njt1982** [comment] 2023-09-12 10:45
Ahh sorry @makkarMeenu - I did search for `placeholderTextColor` and `placeholder` and somehow missed that!
